default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Blog_development
  username: malworm

test:
  <<: *default
  database: Blog_test

production:
  <<: *default
  database: Blog_production
  username: malworm
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
