default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/development.sqlite
  username: malworm

test:
  <<: *default
  database: db/development.sqlite
